# -*- coding: utf-8 -*-
"""knapsack_dp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FA1Y9qvbSngXThyUeOdRONErJFDLDkOL
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile knapsack_dp.py
# # Implementasi 0/1 Knapsack dengan Dynamic Programming
# # Studi Kasus Fore Coffee
# 
weights = [8, 7, 6, 5, 6, 7, 2, 3, 4, 2]
profits = [180, 165, 150, 120, 135, 160, 70, 75, 90, 50]
capacity = 35
n = len(weights)

dp = [[0 for _ in range(capacity + 1)] for _ in range(n + 1)]

for i in range(1, n + 1):
    for w in range(capacity + 1):
        if weights[i - 1] <= w:
            dp[i][w] = max(
                dp[i - 1][w],
                dp[i - 1][w - weights[i - 1]] + profits[i - 1]
            )
        else:
            dp[i][w] = dp[i - 1][w]

w = capacity
selected_items = [0] * n
total_weight = 0

for i in range(n, 0, -1):
    if dp[i][w] != dp[i - 1][w]:
        selected_items[i - 1] = 1
        w -= weights[i - 1]
        total_weight += weights[i - 1]

print("Nilai maksimum:", dp[n][capacity])
print("Daftar item terpilih (0/1):", selected_items)
print("Total berat:", total_weight)
